### ISSUE TITLE
Some questions about routes and controllers

### ISSUE THREAD

**Issue by sergiogragera** [alejandro-albiol/toDoPro#5]
What is the purpose of your controllers?

Currently there are routes where the input data is validated and these call the controller, which is a simple proxy that calls the service. Don't you think that the route is already acting as a controller? You control the input data by doing validations and you control the status and output data (well, in some cases it is not controlled since the password is shown in the output when doing a GET of a user and it shouldn't be).

There is something else that I don't understand: error control. The service returns an object with isSuccess, but this can only handle 2 states. What happens if an endpoint must return several states (for example, when searching for a user by id we could return a 400 if the indicated id is not valid, a 404 if we don't find the user, or a 200 if everything is fine). It's just an example, but you might find problems when you want to handle several states and I assure you that you will need them.

The service should throw errors, for example, throw new UserNotFoundException and the controller for each type of error will be able to control the status to return (404 in this case).

I think that in the design of a REST API the isSuccess field is not necessary since it causes confusion when we have status codes. Do you expect to return a 200 with isSuccess: false? And what does the message field contribute? If you expect to show that message to the user and one day you add i18n to your application that message does not work, it is much better to send an internal code if you do not want to rely only on the status. That is, in the case of updating a user and putting the wrong email or the name longer than allowed we will return 400 but to differentiate it would be good to use an INVALID_EMAIL or INVALID_NAME or NAME_TOO_LONG code that the client (the frontend) knows how to translate into a readable text for the user.

What do you think about this?

Some errors that I have detected with the integration tests of the users route/controller (I will open a PR for you in few days):

GET /api/v1/users/:id
use a response dto to omit password (https://github.com/typestack/class-transformer)

GET /api/v1/users › should returns empty array when no users found but receive null

PUT /api/v1/users/profile/:id › should throw 404 when user not found but receive 400 (is there a security reason for this?)

PUT /api/v1/users/profile/:id › update user by param id, not need to send user with id at body (EditUserDto without id at body for example)

DELETE /api/v1/users/:id › should throw 404 when user not exists but receive 400 (is there a security reason for this?)

**Comment by alejandro-albiol** [comment]
Thank you so much for your detailed feedback! Your suggestions were incredibly valuable and helped me improve my codebase significantly. I've implemented a refactor (currently in the `refactor` branch) focusing on the users flow as a first step:

1. Error Handling Refactor
   - Removed the `isSuccess` pattern in favor of proper error throwing
   - Implemented a comprehensive exception hierarchy starting with `BaseException`
   - Added specific user-related exceptions like `UserNotFoundException`, `UserAuthenticationException`, etc.
   - Now services throw these exceptions and controllers handle them appropriately with proper HTTP status codes

2. Controller/Route Structure
   - Streamlined the user controller layer to handle HTTP concerns and status codes
   - Controller now properly handles different states (400, 404, 200, etc.)
   - Implemented proper separation of concerns between routes and controllers

3. Data Transfer Objects (DTOs)
   - Implemented proper DTOs to control user data exposure
   - Password is no longer exposed in user responses
   - Separated input and output DTOs for better control

4. Code Organization
   - Restructured the project into clear backend/frontend separation
   - Improved folder structure for better maintainability
   - Added proper interfaces for user service and repository

5. Fixed Specific Issues
   - GET /api/v1/users/:id now uses response DTO to omit password
   - GET /api/v1/users now returns empty array instead of null when no users found
   - PUT and DELETE operations now properly return 404 when user not found
   - Removed redundant ID in body for profile updates

I've focused this refactor on the users flow as a proof of concept. Once you validate this approach, I plan to apply the same patterns to the rest of the application.

Would you mind taking a look at these changes in the `refactor` branch and letting me know if this is more aligned with what you had in mind? Your feedback will be valuable before extending these changes to other parts of the application.

P.S.: I'm having some "fun" with Git during this refactor (you know, those moments when Git decides to make things interesting 😅). If you see any weird commits or structure issues, I'm working on cleaning that up. Git and I are currently in relationship counseling! 🤣

**Comment by sergiogragera** [comment]
Good job, really good. I've opened a PR for you on this with some changes.

I really like your unit tests and everything you're building. Congratulations.
